name: Format

on: [workflow_call, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-format-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
 format:
    name: format-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Format Code
      run: cmake -P cmake/Format.cmake

    - name: Check Formatting
      run: git diff --exit-code